version: '3' 

services: 
 
  batch_tools:
    build: ./batch_tools
 
    volumes:
      - batch_volume:/var/lib/brains/.brainspace/BatchTools

    env_file:
      - environments.env
  
  app:
    build: ./app
    
    volumes:
      - batch_volume:/var/lib/brains/.brainspace/BatchTools:ro
    
    depends_on:
      - batch_tools 

    env_file:
      - environments.env  

  analysis_server:
    build: ./analysis_server
    
    volumes:
      - batch_volume:/var/lib/brains/.brainspace/BatchTools:ro
    
    depends_on:
      - batch_tools 

    env_file:
      - environments.env
   

volumes:
  batch_volume:
